export const ProvinceOptions = {
  1: [
    //{ label: "0", value: "لطفا شهر را انتخاب نمایید" },
    { label: "تهران", value: "1" },
    { label: "احمد آباد مستوفی", value: "2" },
    { label: "ادران", value: "3" },
    { label: "اسلام آباد", value: "4" },
    { label: "اسلام شهر", value: "5" },
    { label: "اكبر آباد", value: "6" },
    { label: "اميريه", value: "7" },
    { label: "انديشه", value: "8" },
    { label: "اوشان", value: "9" },
    { label: "آبسرد", value: "10" },
    { label: "آبعلی", value: "11" },
    { label: "باغستان", value: "12" },
    { label: "باقر شهر", value: "13" },
    { label: "برغان", value: "14" },
    { label: "بومهن", value: "15" },
    { label: "پارچين", value: "16" },
    { label: "پاكدشت", value: "17" },
    { label: "پرديس", value: "18" },
    { label: "پرند", value: "19" },
    { label: "پس قلعه", value: "20" },
    { label: "پيشوا", value: "21" },
    { label: "جاجرود", value: "22" },
    { label: "چهار دانگه", value: "23" },
    { label: "حسن آباد", value: "24" },
    { label: "حومه گلندوک", value: "25" },
    { label: "خاتون آباد", value: "26" },
    { label: "خاوه", value: "27" },
    { label: "خرمدشت", value: "28" },
    { label: "دركه", value: "29" },
    { label: "دماوند", value: "30" },
    { label: "رباط كريم", value: "31" },
    { label: "رزگان", value: "32" },
    { label: "رودهن", value: "33" },
    { label: "ری", value: "34" },
    { label: "سعيد آباد", value: "35" },
    { label: "سلطان آباد", value: "36" },
    { label: "سوهانک", value: "37" },
    { label: "شاهد شهر", value: "38" },
    { label: "شريف آباد", value: "39" },
    { label: "شمس آباد", value: "40" },
    { label: "شهر قدس", value: "41" },
    { label: "شهرآباد", value: "42" },
    { label: "شهرجديد پرديس", value: "43" },
    { label: "شهرقدس", value: "44" },
    { label: "شهريار", value: "45" },
    { label: "شهريار بردآباد", value: "46" },
    { label: "صالح آباد", value: "47" },
    { label: "صفادشت", value: "48" },
    { label: "فرودگاه امام خمينی", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // { label: "", value: "49" },
    // ... (other city options)
  ],
  2: [
    //{ value: "0", label: "لطفا شهر را انتخاب نمایید" },
    { value: "1", label: "احمد سرگوراب" },
    { value: "2", label: "اسالم" },
    { value: "3", label: "اسكلک" },
    { value: "4", label: "اسلام آباد" },
    // ... (other city options)
  ],
  // ... (other provinces)
};

export const CityOptions = [
  { value: "1", label: "تهران" },
  { value: "2", label: "گیلان" },
  { value: "3", label: "آذربایجان شرقی" },
  { value: "4", label: "خوزستان" },
  { value: "5", label: "فارس" },
  { value: "6", label: "اصفهان" },
  { value: "7", label: "خراسان رضوی" },
  { value: "8", label: "اصفهان" },
  { value: "9", label: "قزوین" },
  { value: "10", label: "سمنان" },
  { value: "11", label: "قم" },
  { value: "12", label: "مرکزی" },
  { value: "13", label: "زنجان" },
  { value: "14", label: "مازندران" },
  { value: "15", label: "گلستان" },
  { value: "16", label: "اردبیل" },
  { value: "17", label: "آذربایجان غربی" },
  { value: "18", label: "همدان" },
  { value: "19", label: "کردستان" },
  { value: "20", label: "کرمانشاه" },
  { value: "21", label: "لرستان" },
  { value: "22", label: "بوشهر" },
  { value: "23", label: "کرمان" },
  { value: "24", label: "هرمزگان" },
  { value: "25", label: "چهارمحال و بختیاری" },
  { value: "26", label: "یزد" },
  { value: "27", label: "سیستان و بلوچستان" },
  { value: "28", label: "ایلام" },
  { value: "29", label: "کهگلویه و بویراحمد" },
  { value: "30", label: "خراسان شمالی" },
  { value: "31", label: "خراسان جنوبی" },
  { value: "32", label: "البرز" },
];
