export const ProvinceOptions = {
  1: [
    //{ label: "0", value: "لطفا شهر را انتخاب نمایید" },
    { label: "تهران", value: "1" },
    { label: "احمد آباد مستوفی", value: "2" },
    { label: "ادران", value: "3" },
    { label: "اسلام آباد", value: "4" },
    { label: "اسلام شهر", value: "5" },
    { label: "اكبر آباد", value: "6" },
    { label: "اميريه", value: "7" },
    { label: "انديشه", value: "8" },
    { label: "اوشان", value: "9" },
    { label: "آبسرد", value: "10" },
    { label: "آبعلی", value: "11" },
    { label: "باغستان", value: "12" },
    { label: "باقر شهر", value: "13" },
    { label: "برغان", value: "14" },
    { label: "بومهن", value: "15" },
    { label: "پارچين", value: "16" },
    { label: "پاكدشت", value: "17" },
    { label: "پرديس", value: "18" },
    { label: "پرند", value: "19" },
    { label: "پس قلعه", value: "20" },
    { label: "پيشوا", value: "21" },
    { label: "جاجرود", value: "22" },
    { label: "چهار دانگه", value: "23" },
    { label: "حسن آباد", value: "24" },
    { label: "حومه گلندوک", value: "25" },
    { label: "خاتون آباد", value: "26" },
    { label: "خاوه", value: "27" },
    { label: "خرمدشت", value: "28" },
    { label: "دركه", value: "29" },
    { label: "دماوند", value: "30" },
    { label: "رباط كريم", value: "31" },
    { label: "رزگان", value: "32" },
    { label: "رودهن", value: "33" },
    { label: "ری", value: "34" },
    { label: "سعيد آباد", value: "35" },
    { label: "سلطان آباد", value: "36" },
    { label: "سوهانک", value: "37" },
    { label: "شاهد شهر", value: "38" },
    { label: "شريف آباد", value: "39" },
    { label: "شمس آباد", value: "40" },
    { label: "شهر قدس", value: "41" },
    { label: "شهرآباد", value: "42" },
    { label: "شهرجديد پرديس", value: "43" },
    { label: "شهرقدس", value: "44" },
    { label: "شهريار", value: "45" },
    { label: "شهريار بردآباد", value: "46" },
    { label: "صالح آباد", value: "47" },
    { label: "صفادشت", value: "48" },
    { label: "فرودگاه امام خمينی", value: "49" },
    { label: "فرون آباد", value: "50" },
    { label: "فشم", value: "51" },
    { label: "فيروزكوه", value: "52" },
    { label: "قرچک", value: "53" },
    { label: "قيام دشت", value: "54" },
    { label: "كهريزک", value: "55" },
    { label: "كيلان", value: "56" },
    { label: "گلدسته", value: "57" },
    { label: "گلستان", value: "58" },
    { label: "گيلاوند", value: "59" },
    { label: "لواسان", value: "60" },
    { label: "لوسان بزرگ", value: "61" },
    { label: "مارليک", value: "62" },
    { label: "مروزبهرام", value: "63" },
    { label: "ملارد", value: "64" },
    { label: "نسيم شهر", value: "65" },
    { label: "نصيرآباد", value: "66" },
    { label: "واوان", value: "67" },
    { label: "وحيديه", value: "68" },
    { label: "ورامين", value: "69" },
    { label: "وهن آباد", value: "70" },
    // ... (other city options)
  ],
  2: [
    //{ value: "0", label: "لطفا شهر را انتخاب نمایید" },
    { value: "1", label: "احمد سرگوراب" },
    { value: "2", label: "اسالم" },
    { value: "3", label: "اسكلک" },
    { value: "4", label: "اسلام آباد" },
    { value: "5", label: "اسكلک" },
    { value: "6", label: "اطاقور" },
    { value: "7", label: "املش" },
    { value: "8", label: "آبكنار" },
    { value: "9", label: "آستارا" },
    { value: "10", label: "آستانه اشرفيه" },
    { value: "11", label: "بازار اسالم" },
    { value: "12", label: "بازارجمعه شاندرمن" },
    { value: "13", label: "برهسر" },
    { value: "14", label: "بلترک" },
    { value: "15", label: "بلسبنه" },
    { value: "16", label: "بندر انزلی" },
    { value: "17", label: "پاشاكی" },
    { value: "18", label: "پرهسر" },
    { value: "19", label: "پلاسی" },
    { value: "20", label: "پونل" },
    { value: "21", label: "پيربست لولمان" },
    { value: "22", label: "توتكابن" },
    { value: "23", label: "جوكندان" },
    { value: "24", label: "جيرنده" },
    { value: "25", label: "چابكسر" },
    { value: "26", label: "چاپارخانه" },
    { value: "27", label: "چوبر" },
    { value: "28", label: "خاچكين" },
    { value: "29", label: "خشک بيجار" },
    { value: "30", label: "خطبه سرا" },
    { value: "31", label: "خمام" },
    { value: "32", label: "ديلمان" },
    { value: "33", label: "رانكوه" },
    { value: "34", label: "رحيم آباد" },
    { value: "35", label: "رستم آباد" },
    { value: "36", label: "رشت" },
    { value: "37", label: "رضوان شهر" },
    { value: "38", label: "رودبار" },
    { value: "39", label: "رودسر" },
    { value: "40", label: "سراوان" },
    { value: "41", label: "سنگر" },
    { value: "42", label: "سياهكل" },
    { value: "43", label: "شاندرمن" },
    { value: "44", label: "شفت" },
    { value: "45", label: "صومعه سرا" },
    { value: "46", label: "طاهر گودا" },
    { value: "47", label: "طوللات" },
    { value: "48", label: "فومن" },
    { value: "49", label: "قاسم آبادسفلی" },
    { value: "50", label: "كپورچال" },
    { value: "51", label: "كلاچای" },
    { value: "52", label: "كوچصفهان" },
    { value: "53", label: "كومله" },
    { value: "54", label: "كياشهر" },
    { value: "55", label: "گشت" },
    { value: "56", label: "لاهيجان" },
    { value: "57", label: "لشت نشا" },
    { value: "58", label: "لنگرود" },
    { value: "59", label: "لوشان" },
    { value: "60", label: "لولمان" },
    { value: "61", label: "لوندويل" },
    { value: "62", label: "ليسار" },
    { value: "63", label: "ماسال" },
    { value: "64", label: "ماسوله" },
    { value: "65", label: "منجيل" },
    { value: "66", label: "هشتپر ـ طوالش" },
    { value: "67", label: "واجارگاه" },
    { value: "68", label: "چمخاله" },

    // ... (other city options)
  ],
  3: [
    { label: "ابشاحمد", value: "1" },
    { label: "اذغان", value: "2" },
    { label: "اسب فروشان", value: "3" },
    { label: "اسكو", value: "4" },
    { label: "اغچه ريش", value: "5" },
    { label: "اقمنار", value: "6" },
    { label: "القو", value: "7" },
    { label: "اهر", value: "8" },
    { label: "ايلخچی", value: "9" },
    { label: "آذرشهر", value: "10" },
    { label: "باسمنج", value: "11" },
    { label: "بخشايش ـ كلوانق", value: "12" },
    { label: "بستان آباد", value: "13" },
    { label: "بناب", value: "14" },
    { label: "بناب جديد ـ مرند", value: "15" },
    { label: "تبريز", value: "16" },
    { label: "ترک", value: "17" },
    { label: "تسوج", value: "18" },
    { label: "جلفا", value: "19" },
    { label: "خامنه", value: "20" },
    { label: "خداآفرين", value: "21" },
    { label: "خسروشهر", value: "22" },
    { label: "خضرلو", value: "23" },
    { label: "خلجان", value: "24" },
    { label: "سبلان", value: "25" },
    { label: "سراب", value: "26" },
    { label: "سردرود", value: "27" },
    { label: "سيس", value: "28" },
    { label: "شادباد مشايخ", value: "29" },
    { label: "شبستر", value: "30" },
    { label: "شربيان", value: "31" },
    { label: "شرفخانه", value: "32" },
    { label: "شهرجديد سهند", value: "33" },
    { label: "صوفيان", value: "34" },
    { label: "عجب شير", value: "35" },
    { label: "قره اغاج ـ چاراويماق", value: "36" },
    { label: "قره بابا", value: "37" },
    { label: "كردكندی", value: "38" },
    { label: "كليبر", value: "39" },
    { label: "كندرود", value: "40" },
    { label: "كندوان", value: "41" },
    { label: "گوگان", value: "42" },
    { label: "مراغه", value: "43" },
    { label: "مرند", value: "44" },
    { label: "ملكان", value: "45" },
    { label: "ممقان", value: "46" },
    { label: "ميانه", value: "47" },
    { label: "هاديشهر", value: "48" },
    { label: "هريس", value: "49" },
    { label: "هشترود", value: "50" },
    { label: "هوراند", value: "51" },
    { label: "ورزقان", value: "52" },
  ],
  4: [
    { label: "", value: "1" },
    { label: "", value: "2" },
    { label: "", value: "3" },
    { label: "", value: "4" },
    { label: "", value: "5" },
    { label: "", value: "6" },
    { label: "", value: "7" },
    { label: "", value: "8" },
    { label: "", value: "9" },
  ],
};

export const CityOptions = [
  { value: "1", label: "تهران" },
  { value: "2", label: "گیلان" },
  { value: "3", label: "آذربایجان شرقی" },
  { value: "4", label: "خوزستان" },
  { value: "5", label: "فارس" },
  { value: "6", label: "اصفهان" },
  { value: "7", label: "خراسان رضوی" },
  { value: "8", label: "اصفهان" },
  { value: "9", label: "قزوین" },
  { value: "10", label: "سمنان" },
  { value: "11", label: "قم" },
  { value: "12", label: "مرکزی" },
  { value: "13", label: "زنجان" },
  { value: "14", label: "مازندران" },
  { value: "15", label: "گلستان" },
  { value: "16", label: "اردبیل" },
  { value: "17", label: "آذربایجان غربی" },
  { value: "18", label: "همدان" },
  { value: "19", label: "کردستان" },
  { value: "20", label: "کرمانشاه" },
  { value: "21", label: "لرستان" },
  { value: "22", label: "بوشهر" },
  { value: "23", label: "کرمان" },
  { value: "24", label: "هرمزگان" },
  { value: "25", label: "چهارمحال و بختیاری" },
  { value: "26", label: "یزد" },
  { value: "27", label: "سیستان و بلوچستان" },
  { value: "28", label: "ایلام" },
  { value: "29", label: "کهگلویه و بویراحمد" },
  { value: "30", label: "خراسان شمالی" },
  { value: "31", label: "خراسان جنوبی" },
  { value: "32", label: "البرز" },
];
