export const ProvinceOptions = {
  1: [
    //{ label: "0", value: "لطفا شهر را انتخاب نمایید" },
    { label: "تهران", value: "1" },
    { label: "پردیس", value: "2" },
    { label: "ری", value: "3" },
    { label: "رباط کریم", value: "4" },
    { label: "شهریار", value: "5" },
    { label: "ورامین", value: "6" },
    { label: "بهارستان", value: "7" },
    { label: "شریف آباد", value: "8" },
    { label: "چهاردانگه", value: "9" },
    { label: "شهرقدس", value: "10" },
    { label: "بومهن", value: "11" },
    { label: "اسلام شهر", value: "12" },
    { label: "پاکدشت", value: "13" },
    { label: "قرچک", value: "14" },
    { label: "کهریزک", value: "15" },
    { label: "رودهن", value: "16" },
    { label: "حسن آباد", value: "17" },
    { label: "پرند", value: "18" },
    { label: "باقر شهر", value: "19" },
    { label: "آبسرد", value: "20" },
    { label: "فیروزکوه", value: "21" },
    { label: "ملارد", value: "22" },
    { label: "صفا دشت", value: "23" },
    { label: "دماوند", value: "24" },
    { label: "کمالشهر", value: "25" },
    { label: "آبعلی", value: "26" },
    { label: "محمد شهر", value: "27" },
    { label: "قیامدشت", value: "28" },
    { label: "جاجرود", value: "29" },
    { label: "پرندک", value: "30" },
    { label: "پیشوا", value: "31" },
    { label: "رودباران قصران", value: "32" },
    { label: "لوسانات", value: "33" },
    { label: "شمیرانات", value: "34" },
  ],
  2: [
    //{ value: "0", label: "لطفا شهر را انتخاب نمایید" },
    { value: "35", label: "رشت" },
    { value: "36", label: "بندرانزلی" },
    { value: "37", label: "آستارا" },
    { value: "38", label: "لاهیجان" },
    { value: "39", label: "لوشان" },
    { value: "40", label: "هشت پر" },
    { value: "41", label: "بندر کیانشهر" },
    { value: "42", label: "کوچصفهان" },
    { value: "43", label: "کلاچای" },
    { value: "44", label: "آستانه اشرفيه" },
    { value: "45", label: "رضوان شهر" },
    { value: "46", label: "ماسال" },
    { value: "47", label: "طوالش" },
    { value: "48", label: "رستم آباد" },
    { value: "49", label: "رودبار" },
    { value: "50", label: "املش" },
    { value: "51", label: "رودسر" },
    { value: "52", label: "صومعه سرا" },
    { value: "53", label: "شفت" },
    { value: "54", label: "فومن" },
    { value: "55", label: "سیاهکل" },
    { value: "56", label: "لنگرود" },
    { value: "57", label: "اسالم" },
    { value: "58", label: "چابکسر" },
    { value: "59", label: "تالش" },
    { value: "60", label: "خشکبیجار" },
    { value: "61", label: "منجیل" },
    { value: "62", label: "سنگسر" },
  ],
  3: [
    { label: "تبریز", value: "63" },
    { label: "ممقان", value: "64" },
    { label: "خسرو شهر", value: "65" },
    { label: "خراجو", value: "66" },
    { label: "اهر", value: "67"},
    { label: "ورزقان", value: "68" },
    { label: "آذرشهر", value: "69" },
    { label: "اسکو", value: "70" },
    { label: "بستان آباد", value: "71" },
    { label: "شبستر", value: "72" },
    { label: "خاروانا", value: "73" },
    { label: "سراب", value: "74" },
    { label: "هادی شهر", value: "75" },
    { label: "کلیبر", value: "76" },
    { label: "بناب", value: "77" },
    { label: "عجب شیر", value: "78" },
    { label: "مراغه", value: "79" },
    { label: "ملکان", value: "80" },
    { label: "جلفا", value: "81" },
    { label: "مرند", value: "82" },
    { label: "ترکمنچای", value: "83" },
    { label: "میانه", value: "84" },
    { label: "هریس", value: "85" },
    { label: "چاراویماق", value: "86" },
    { label: "هشترود", value: "87" },
    { label: "قره اغاج", value: "88" },
    { label: "خدا آفرین", value: "89" },
    { label: "مهربان", value: "90" },
  ],
  4: [
    { label: "اهواز", value: "91" },
    { label: "بندرماهشهر", value: "92" },
    { label: "بندر امام خمینی", value: "93" },
    { label: "امیدیه", value: "94" },
    { label: "آبادان", value: "95" },
    { label: "صیدون", value: "96" },
    { label: "سردشت دزفول", value: "97" },
    { label: "اروند کنار", value: "98" },
    { label: "گتوند", value: "99" },
    { label: "شوشتر", value: "100" },
    { label: "لالی", value: "101" },
    { label: "مسجد سلیمان", value: "102" },
    { label: "شوش", value: "103" },
    { label: "لالی", value: "104" },
    { label: "مسجد سلیمان", value: "105" },
    { label: "شوش", value: "106" },
    { label: "حمیدیه", value: "107" },
    { label: "ایذه", value: "108" },
    { label: "اندیمشک", value: "109" },
    { label: "دهدز", value: "110" },
    { label: "باغملک", value: "111" },
    { label: "هویزه", value: "112" },
    { label: "هندیجان", value: "113" },
    { label: "بهبهان", value: "114" },
    { label: "خرمشهر", value: "115" },
    { label: "دزفول", value: "116" },
    { label: "دشت آزادگان", value: "117" },
    { label: "رامشیر", value: "118" },
    { label: "رامهرمز", value: "119" },
    { label: "شادگان", value: "120" },
    { label: "اغاجاری", value: "121" },
    { label: "بستان", value: "122" },
    { label: "سوسنگرد", value: "123" },
    { label: "الوان", value: "124" },
    { label: "شاوور", value: "125" },
    { label: "اندیکا(قلعه خواجو)", value: "126" },
    { label: "باوی", value: "127" },
  ],
  5: [
    { label: "شیراز", value: "128" },
    { label: "مرودشت", value: "129" },
    { label: "دشمن زیاری", value: "130" },
    { label: "فراشبند", value: "131" },
    { label: "قیروکارزین", value: "132" },
    { label: "فیروزآباد", value: "133" },
    { label: "بالاده", value: "134" },
    { label: "درودزن", value: "135" },
    { label: "شیب کوه", value: "136" },
    { label: "کازرون", value: "137" },
    { label: "فسا", value: "138" },
    { label: "سپیدان", value: "139" },
    { label: "زرقان", value: "140" },
    { label: "آباده طشک", value: "141" },
    { label: "لامرد", value: "142" },
    { label: "لارستان", value: "143" },
    { label: "مهر", value: "144" },
    { label: "داراب", value: "145" },
    { label: "زرین دشت", value: "146" },
    { label: "قائمیه", value: "147" },
    { label: "جهرم", value: "148" },
    { label: "اقلید", value: "149" },
    { label: "استهبان", value: "150" },
    { label: "ارسنجان", value: "151" },
    { label: "ممسنی (نورآباد)", value: "152" },
    { label: "نی ریز", value: "153" },
    { label: "سرچهان", value: "154" },
    { label: "پاسارگاد", value: "155" },
    { label: "قادرآباد", value: "156" },
    { label: "سمیکان", value: "157" },
    { label: "ایزدخواست", value: "158" },
    { label: "قطب آباد", value: "159" },
    { label: "خرم بید", value: "160" },
    { label: "آباده", value: "161" },
    { label: "کامفیروز", value: "162" },
    { label: "بیضا", value: "163" },
    { label: "اشکنان", value: "164" },
    { label: "مهر فارس", value: "165" },
    { label: "سعادت شهر", value: "166" },
    { label: "خاوران", value: "167" },
    { label: "صفا شهر", value: "168" },
    { label: "خنج", value: "169" },
    { label: "رستم", value: "170" },
    { label: "زاهد شهر", value: "171" },
    { label: "نودان", value: "172" },
    { label: "سروستان", value: "173" },
    { label: "خرامه", value: "174" },
    { label: "کوار", value: "175" },
    { label: "لار", value: "176" },
    { label: "بناب جدید", value: "177" },
    { label: "گراش", value: "178" },
  ],
  6: [
    { label: "اصفهان", value: "179" },
    { label: "کاشان", value: "180" },
    { label: "شاهین شهر (میمه)", value: "181" },
    { label: "شهررضا", value: "182" },
    { label: "گلپایگان", value: "183" },
    { label: "مبارکه", value: "184" },
    { label: "نایین", value: "185" },
    { label: "نجف آباد", value: "186" },
    { label: "نطنز", value: "187" },
    { label: "بهارستان", value: "188" },
    { label: "بن رود", value: "189" },
    { label: "نوش اباد", value: "190" },
    { label: "باغ شاد", value: "191" },
    { label: "زواره", value: "192" },
    { label: "ورزنه", value: "193" },
    { label: "حسن آباد جرقویه", value: "194" },
    { label: "کوهپایه", value: "195" },
    { label: "هرند", value: "196" },
    { label: "دولت آباد", value: "197" },
    { label: "خوراسگان", value: "198" },
    { label: "زاینده رود", value: "199" },
    { label: "دهاقان", value: "200" },
    { label: "گز", value: "201" },
    { label: "برزک", value: "202" },
    { label: "فولاد شهر", value: "203" },
    { label: "پیربکران", value: "204" },
    { label: "وزوان", value: "205" },
    { label: "بوئین و میاندشت", value: "206" },
    { label: "زرین شهر", value: "207" },
    { label: "میمه", value: "208" },
    { label: "باغ بهادران", value: "209" },
    { label: "خمینی شهر", value: "210" },
    { label: "اردستان", value: "211" },
    { label: "خوانسار", value: "212" },
    { label: "سمیرم", value: "213" },
    { label: "چادگان", value: "214" },
    { label: "فریدن", value: "215" },
    { label: "فریدون شهر", value: "216" },
    { label: "داران", value: "217" },
    { label: "فلاورجان", value: "218" },
    { label: "اران و بیدگل", value: "219" },
    { label: "لنجان", value: "220" },
    { label: "خور و بیابانک", value: "221" },
    { label: "تیران و کرون", value: "222" },
    { label: "مهردشت (علویجه)", value: "223" },
    { label: "قمصر", value: "224" },
  ],
  7: [
    { label: "مشهد", value: "225" },
    { label: "سبزوار", value: "226" },
    { label: "نیشابور", value: "227" },
    { label: "زبرخان بقدمگاه", value: "228" },
    { label: "عشق آباد", value: "229" },
    { label: "فیروزه", value: "230" },
    { label: " جوین - نقاب", value: "231" },
    { label: " کاخک", value: "232" },
    { label: " تخت جلگه", value: "233" },
    { label: "خواف", value: "234" },
    { label: "جغتای", value: "235" },
    { label: "تایباد", value: "236" },
    { label: " تربت جام", value: "237" },
    { label: "مه ولات - فیض آباد", value: "238" },
    { label: "تربت حدریه", value: "239" },
    { label: "بینالود", value: "240" },
    { label: "چناران", value: "241" },
    { label: "فریمان", value: "242" },
    { label: "کلات", value: "243" },
    { label: "بردسکن", value: "244" },
    { label: "خلیل آباد", value: "245" },
    { label: "کاشمر", value: "246" },
    { label: "قوچان", value: "247" },
    { label: "بجستان", value: "248" },
    { label: "گناباد", value: "249" },
    { label: "سرخس", value: "250" },
    { label: "درگز", value: "251" },
    { label: "درود", value: "252" },
    { label: "سرولایت", value: "253" },
    { label: "دوغارون", value: "254" },
    { label: "داورزن", value: "255" },
    { label: "گلبهار", value: "256" },
    { label: "دولت آباد زاوه", value: "257" },
    { label: "طرقبه", value: "258" },
    { label: "میان جلگه", value: "259" },
    { label: "رشتخوار", value: "260" },
  ],
  8: [
    { label: "قزوین", value: "261" },
    { label: "اوج", value: "262" },
    { label: "الوند", value: "263" },
    { label: "دانسفهان", value: "264" },
    { label: "شال", value: "265" },
    { label: "تاکستان", value: "266" },
    { label: "ابیک", value: "267" },
    { label: "ضیا آباد", value: "268" },
    { label: "بوئین زهرا", value: "269" },
    { label: "طارم سلفی", value: "270" },
    { label: "شهر صنعتی البرز", value: "271" },
  ],
  9: [
    { label: "سمنان", value: "272" },
    { label: "شاهرود", value: "273" },
    { label: "دامغان", value: "274" },
    { label: "بسطام", value: "275" },
    { label: "شهمیرزاد", value: "276" },
    { label: "گرمسار", value: "277" },
    { label: "سرخه", value: "278" },
    { label: "ارادان", value: "279" },
    { label: "میامی", value: "280" },
    { label: "مهدی شهر", value: "281" },
    { label: "ایوانکی", value: "282" },
    { label: "مجن", value: "283" },
  ],
  10: [
    { label: "قم", value: "284" },
    { label: "سلفچگان", value: "285" },
    { label: "جعفریه", value: "286" },
    { label: "دستجرد خلجستان", value: "287" },
    { label: "کهک", value: "288" },
  ],
  11: [
    { label: "اراک", value: "289" },
    { label: "سربند", value: "290" },
    { label: "شهرک صنعتی نوبران", value: "291" },
    { label: "خنداب", value: "292" },
    { label: "(چهار چشمه) قورچی باشی", value: "293" },
    { label: "غرق آباد", value: "294" },
    { label: "کمیجان", value: "295" },
    { label: "اشتیان", value: "296" },
    { label: "تفرش", value: "297" },
    { label: "خمین", value: "298" },
    { label: "دلیجان", value: "299" },
    { label: "زرندیه", value: "300" },
    { label: "ساوه", value: "301" },
    { label: "شازند", value: "302" },
    { label: "مهاجران", value: "303" },
    { label: "محلات", value: "304" },
  ],
  12: [
    { label: "زنجان", value: "305" },
    { label: "ابهر", value: "306" },
    { label: "صائین قلعه", value: "307" },
    { label: "قیدار", value: "308" },
    { label: "طارم", value: "309" },
    { label: "سلطانیه", value: "310" },
    { label: "ماه نشان", value: "311" },
    { label: "ایجرود (زرین آباد)", value: "312" },
    { label: "خدابنده", value: "313" },
    { label: "خرمدره", value: "314" },
    { label: "بزینه رود", value: "315" },
  ],
  13: [
    { label: "ساری", value: "316" },
    { label: "آمل", value: "317" },
    { label: "بابل", value: "318" },
    { label: "بابلسر", value: "319" },
    { label: "رامسر", value: "320" },
    { label: "چالوس", value: "321" },
    { label: "نوضهر", value: "322" },
    { label: "قائم شهر", value: "323" },
    { label: "محمو آباد", value: "324" },
    { label: "بندپی شرقی", value: "325" },
    { label: "کلاردشت", value: "326" },
    { label: "هراز", value: "327" },
    { label: "بهشهر", value: "328" },
    { label: "نکا", value: "329" },
    { label: "تنکابن", value: "330" },
    { label: "گلوگاه", value: "331" },
    { label: "سوادکوه", value: "332" },
    { label: "نور", value: "333" },
    { label: "بهنمیر", value: "334" },
    { label: "رینه", value: "335" },
    { label: "بندپی غربی", value: "336" },
    { label: "عباس آباد", value: "337" },
    { label: "فریدون کنار", value: "338" },
    { label: "کله بست", value: "339" },
    { label: "پل سفید", value: "340" },
    { label: "زیراب", value: "341" },
    { label: "چمستان", value: "342" },
    { label: "امیرکلا", value: "343" },
    { label: "میاندورود", value: "344" },
    { label: "جویبار", value: "345" },
  ],
  14: [
    { label: "گرگان", value: "346" },
    { label: "بندر ترکمن", value: "347" },
    { label: "گنبد کاووس", value: "348" },
    { label: "گمیشان", value: "349" },
    { label: "مراوه تپه", value: "350" },
    { label: "بندرگز", value: "351" },
    { label: "کردکوی", value: "352" },
    { label: "اق قلا", value: "353" },
    { label: "گالیکش", value: "354" },
    { label: "آزادشهر", value: "355" },
    { label: "رامیاران", value: "356" },
    { label: "مینودشت", value: "357" },
    { label: "علی آباد کتول", value: "358" },
    { label: "کلاله", value: "359" },
  ],
  15: [
    { label: "اردبیل", value: "360" },
    { label: "سرعین", value: "361" },
    { label: "مشکین شهر", value: "362" },
    { label: "بیله سوار", value: "363" },
    { label: "پارس آباد", value: "364" },
    { label: "گرمی", value: "365" },
    { label: " تازه انگوت", value: "366" },
    { label: " ارشق (رضی)", value: "367" },
    { label: " کوثر", value: "368" },
    { label: "هیر", value: "369" },
    { label: "خلخال", value: "370" },
    { label: "نمین", value: "371" },
    { label: "مغان", value: "372" },
    { label: "اصلاندوز", value: "373" },
  ],
  16: [
    { label: "ارومیه", value: "374" },
    { label: "سیلوانا", value: "375" },
    { label: " صومای برادوست", value: "376" },
    { label: "نازلو", value: "377" },
    { label: "گوگ تپه", value: "378" },
    { label: "ابواوغلی", value: "379" },
    { label: "چهاربرج", value: "380" },
    { label: "سیه چشمه", value: "381" },
    { label: "تازه شهر", value: "382" },
    { label: "شوط", value: "383" },
    { label: "چایپاره", value: "384" },
    { label: "پیرانشهر", value: "385" },
    { label: " سلماس", value: "386" },
    { label: "پلدشت", value: "387" },
    { label: "چالدران", value: "388" },
    { label: "ماکو", value: "389" },
    { label: "قره ضیاء الدین", value: "390" },
    { label: "بوکان", value: "391" },
    { label: "خوی", value: "392" },
    { label: "سردشت", value: "393" },
    { label: "مهاباد", value: "394" },
    { label: "تکاب", value: "395" },
    { label: "شاهین دژ", value: "396" },
    { label: "میاندوآب", value: "397" },
    { label: "اشنویه", value: "398" },
    { label: "نقده", value: "399" },
  ],
  17: [
    { label: "همدان", value: "400" },
    { label: "قروه ", value: "401" },
    { label: "سامن", value: "402" },
    { label: "لالیجن", value: "403" },
    { label: "صالح آباد", value: "404" },
    { label: "تویسرکان", value: "405" },
    { label: "کبودرآهنگ", value: "406" },
    { label: "ملایر", value: "407" },
    { label: " نهاوند", value: "408" },
    { label: "اسد آباد", value: "409" },
    { label: "رزن", value: "410" },
    { label: "بهار", value: "411" },
  ],
  18: [
    { label: "سنندج", value: "412" },
    { label: "سقز", value: "413" },
    { label: "دیواندره", value: "414" },
    { label: "کامیاران", value: "415" },
    { label: "قروه", value: "416" },
    { label: "دهگلان", value: "417" },
    { label: "سروآباد", value: "418" },
    { label: "مریوان", value: "419" },
    { label: "بانه", value: "420" },
    { label: "بیجار", value: "421" },
  ],
  19: [
    { label: "کرمانشاه", value: "422" },
    { label: "تازه آباد", value: "423" },
    { label: "گلانغرب", value: "424" },
    { label: "کنگاور", value: "425" },
    { label: "قصر شیرین", value: "426" },
    { label: "سنقر", value: "427" },
    { label: "پاوه ", value: "428" },
    { label: "جوانرود ", value: "429" },
    { label: "روانسر ", value: "430" },
    { label: "سرپل ذهاب", value: "431" },
    { label: "صحنه", value: "432" },
    { label: "اسلام آباد غرب", value: "433" },
    { label: " هرسین", value: "434" },
    { label: "ثلاث باباجانی", value: "435" },
    { label: "دالاهو", value: "436" },
  ],
  20: [
    { label: "خرم آباد", value: "437" },
    { label: "بروجرد", value: "438" },
    { label: "الشتر", value: "439" },
    { label: "دروه", value: "440" },
    { label: "ازنا", value: "441" },
    { label: "الیگودرز", value: "442" },
    { label: "سلسله ", value: "443" },
    { label: "پلدختر", value: "444" },
    { label: "دورود", value: "445" },
    { label: "دلفان (نورآباد)", value: "446" },
    { label: "رومشکان", value: "447" },
    { label: "کوهدشت", value: "448" },
  ],
  21: [
    { label: "بوشهر", value: "449" },
    { label: "جم", value: "450" },
    { label: "سعدآباد", value: "451" },
    { label: "دلوار", value: "452" },
    { label: "بندر دیر", value: "453" },
    { label: "اهرم(تنگستان)", value: "454" },
    { label: "عسلویه", value: "455" },
    { label: "دشتی خورموج", value: "456" },
    { label: "دیر(بردخون)", value: "457" },
    { label: "دیلم", value: "458" },
    { label: "بندر گناوه", value: "459" },
    { label: "شبانکاره", value: "460" },
    { label: "دشتستان (برازجان)", value: "461" },
    { label: "کنگان", value: "462" },
  ],
  22: [
    { label: "کرمان", value: "463" },
    { label: "رودبار جنوب", value: "464" },
    { label: "بافت", value: "465" },
    { label: "بردسیر", value: "466" },
    { label: "بم", value: "467" },
    { label: "عنبرآباد", value: "468" },
    { label: "جیرفت", value: "469" },
    { label: "رفسنجان", value: "470" },
    { label: "کوهبنان", value: "471" },
    { label: "زرند", value: "472" },
    { label: "سیرجان", value: "473" },
    { label: "شهربابک", value: "474" },
    { label: "قلعه گنج", value: "475" },
    { label: "راور", value: "476" },
    { label: "کهنوج", value: "477" },
    { label: "منوجان", value: "478" },
    { label: "ماهان", value: "479" },
    { label: "فاریاب", value: "480" },
    { label: "پاریز", value: "481" },
    { label: "نگار", value: "482" },
    { label: "رابر", value: "483" },
    { label: "نرماشیر", value: "484" },
    { label: "فهرج", value: "485" },
    { label: "راین", value: "486" },
    { label: "شهداد", value: "487" },
    { label: "انار", value: "488" },
    { label: "کشکوییه", value: "489" },
    { label: "ریگان", value: "490" },
    { label: "زنگی آباد", value: "491" },
    { label: "گلباف", value: "492" },
  ],
  23: [
    { label: "بندرعباس", value: "493" },
    { label: "کیش", value: "494" },
    { label: "ابوموسی", value: "495" },
    { label: "قشم", value: "496" },
    { label: "حاجی آباد", value: "497" },
    { label: "بستک", value: "498" },
    { label: "بندر لنگه", value: "499" },
    { label: "جاسک", value: "500" },
    { label: "میناب", value: "501" },
    { label: "جناح", value: "502" },
    { label: "شهاب", value: "503" },
    { label: "پارسیان", value: "504" },
    { label: "بیابان سیریک", value: "505" },
    { label: "بندر خمیر", value: "506" },
    { label: "دهبارز (رودان)", value: "507" },
    { label: "فین", value: "508" },
    { label: "بشاگرد", value: "509" },
    { label: "سعادت آباد", value: "510" },
  ],
  24: [
    { label: "شهرکرد", value: "511" },
    { label: "خانمیرزا", value: "512" },
    { label: "فلارد", value: "513" },
    { label: "کوهرنگ", value: "514" },
    { label: "فارسان", value: "515" },
    { label: "لردگان", value: "516" },
    { label: "اردل", value: "517" },
    { label: "بروجن", value: "518" },
    { label: "کیار", value: "519" },
    { label: "شلمزار", value: "520" },
    { label: "سامان", value: "521" },
    { label: "فرخ بخش", value: "522" },
    { label: "بلداجی", value: "523" },
    { label: "گندمان", value: "524" },
  ],
  25: [
    { label: "یزد", value: "525" },
    { label: "اردکان", value: "526" },
    { label: "میبد", value: "527" },
    { label: "بافق", value: "528" },
    { label: "لبرکوه", value: "529" },
    { label: "تفت", value: "530" },
    { label: "مهرریز", value: "531" },
    { label: "خاتم", value: "532" },
    { label: "اشکذر", value: "533" },
    { label: "مروست", value: "534" },
    { label: "بهاباد", value: "535" },
    { label: "هرات", value: "536" },
  ],
  26: [
    { label: "زاهدان", value: "537" },
    { label: "زابل", value: "538" },
    { label: "هیرمند", value: "539" },
    { label: "راسک", value: "540" },
    { label: "سیب وسوران", value: "541" },
    { label: "زهک", value: "542" },
    { label: "سرباز", value: "543" },
    { label: "ایرانشهر", value: "544" },
    { label: "چابهار", value: "545" },
    { label: "نیک شهر", value: "546" },
    { label: "خاش", value: "547" },
    { label: "شهرکی و نارویی", value: "548" },
    { label: "سراوان", value: "549" },
    { label: "دشتیاری", value: "550" },
    { label: "بمپور", value: "551" },
    { label: "دلگان", value: "552" },
    { label: "زابلی", value: "553" },
    { label: "پشت آب", value: "554" },
    { label: "شیب آب", value: "555" },
    { label: "قصرقند", value: "556" },
    { label: "لاشار", value: "557" },
    { label: "کنارک", value: "558" },
  ],
  27: [
    { label: "ایلام", value: "559" },
    { label: "ایوان", value: "560" },
    { label: "آبدانان  ", value: "561" },
    { label: "دره شهر", value: "562" },
    { label: "شیروان و چرداول", value: "563" },
    { label: "دهلران", value: "564" },
    { label: "مهران", value: "565" },
    { label: "بدره", value: "566" },
    { label: "سیروان", value: "567" },
    { label: "موسیان", value: "568" },
    { label: "سرآبله", value: "569" },
    { label: "زرین آباد", value: "570" },
    { label: "هلیلان", value: "571" },
    { label: "ملکشاهی", value: "572" },
  ],
  28: [
    { label: "بویراحمد (یاسوج)", value: "573" },
    { label: "گچساران", value: "574" },
    { label: "دنا", value: "575" },
    { label: "بهمئی", value: "576" },
    { label: "دهدشت (کهگیلویه)", value: "577" },
    { label: "سی سخت", value: "578" },
    { label: "دو گنبدان", value: "579" },
    { label: "چرام", value: "580" },
    { label: "لیکک", value: "581" },
    { label: "باشت", value: "582" },
    { label: "مارگون", value: "583" },
  ],
  29: [
    { label: "بجنورد", value: "584" },
    { label: "اشخانه", value: "585" },
    { label: "رازوجرگلان", value: "586" },
    { label: "گرمه", value: "587" },
    { label: "اسفراین", value: "588" },
    { label: "جاجرم", value: "589" },
    { label: "مانه و سملقان", value: "590" },
    { label: "شیروان", value: "591" },
    { label: "فاروج ", value: "592" },
    { label: "غلامان", value: "593" },
  ],
  30: [
    { label: "بیرجند", value: "594" },
    { label: "طبس", value: "595" },
    { label: "فردوس", value: "596" },
    { label: "حاجی آباد", value: "597" },
    { label: "قائنات", value: "598" },
    { label: "بشرویه", value: "599" },
    { label: " نهبندان", value: "600" },
    { label: "سربیشه", value: "601" },
    { label: "زیرکوه", value: "602" },
    { label: "قائن", value: "603" },
    { label: "اسدیه", value: "604" },
    { label: "درمیان", value: "605" },
  ],
  31: [
    { label: "کرج", value: "606" },
    { label: "فردیس کرج", value: "607" },
    { label: "طالقان", value: "608" },
    { label: "هشتگرد", value: "609" },
    { label: "اشتهارد", value: "610" },
    { label: "گرمدره", value: "611" },
    { label: "ماهدشت", value: "612" },
    { label: "ساوجبلاغ", value: "613" },
    { label: "نظرآباد", value: "614" },
  ],
  32: [
    { label: "خاورمیانه", value: "615" },
    { label: "اروپا", value: "616" },
    { label: "اسیای شرقی", value: "617" },
    { label: "امریکای شمالی", value: "618" },
    { label: "امریکای جنوبی", value: "619" },
    { label: "استرالیا", value: "620" },
  ],
};

export const CityOptions = [
  { value: "1", label: "تهران" }, //1
  { value: "2", label: "گیلان" }, //11
  { value: "3", label: "آذربایجان شرقی" }, //10
  { value: "4", label: "خوزستان" }, //13
  { value: "5", label: "فارس" }, //5
  { value: "6", label: "اصفهان" }, //2
  { value: "7", label: "خراسان رضوی" }, //4
  // { value: "8", label: "اصفهان" },
  { value: "8", label: "قزوین" }, //7
  { value: "9", label: "سمنان" }, //18
  { value: "10", label: "قم" }, //6
  { value: "11", label: "مرکزی" }, //14
  { value: "12", label: "زنجان" }, //17
  { value: "13", label: "مازندران" }, //8
  { value: "14", label: "گلستان" }, //28
  { value: "15", label: "اردبیل" }, //16
  { value: "16", label: "آذربایجان غربی" }, //15
  { value: "17", label: "همدان" }, //31
  { value: "18", label: "کردستان" }, //25
  { value: "19", label: "کرمانشاه" }, //26
  { value: "20", label: "لرستان" }, //29
  { value: "21", label: "بوشهر" }, //20
  { value: "22", label: "کرمان" }, //9
  { value: "23", label: "هرمزگان" }, //30
  { value: "24", label: "چهارمحال و بختیاری" }, //21
  { value: "25", label: "یزد" }, //12
  { value: "26", label: "سیستان و بلوچستان" }, //24
  { value: "27", label: "ایلام" }, //19
  { value: "28", label: "کهگلویه و بویراحمد" }, //27
  { value: "29", label: "خراسان شمالی" }, //22
  { value: "30", label: "خراسان جنوبی" }, //23
  { value: "31", label: "البرز" }, //3
  { value: "32", label: "خارج کشور" }, //3
];
