export const ProvinceOptions = {
  1: [
    //{ label: "0", value: "لطفا شهر را انتخاب نمایید" },
    { label: "تهران", value: "1" },
    { label: "پردیس", value: "2" },
    { label: "ری", value: "3" },
    { label: "رباط کریم", value: "4" },
    { label: "شهریار", value: "5" },
    { label: "ورامین", value: "6" },
    { label: "بهارستان", value: "7" },
    { label: "شریف آباد", value: "8" },
    { label: "چهاردانگه", value: "9" },
    { label: "شهرقدس", value: "10" },
    { label: "بومهن", value: "11" },
    { label: "اسلام شهر", value: "12" },
    { label: "پاکدشت", value: "13" },
    { label: "قرچک", value: "14" },
    { label: "کهریزک", value: "15" },
    { label: "رودهن", value: "16" },
    { label: "حسن آباد", value: "17" },
    { label: "پرند", value: "18" },
    { label: "باقر شهر", value: "19" },
    { label: "آبسرد", value: "20" },
    { label: "فیروزکوه", value: "21" },
    { label: "ملارد", value: "22" },
    { label: "صفا دشت", value: "23" },
    { label: "دماوند", value: "24" },
    { label: "کمالشهر", value: "25" },
    { label: "آبعلی", value: "26" },
    { label: "محمد شهر", value: "27" },
    { label: "قیامدشت", value: "28" },
    { label: "جاجرود", value: "29" },
    { label: "پرندک", value: "30" },
    { label: "پیشوا", value: "31" },
    { label: "رودباران قصران", value: "32" },
    { label: "لوسانات", value: "33" },
    { label: "شمیرانات", value: "34" },
  ],
  2: [
    //{ value: "0", label: "لطفا شهر را انتخاب نمایید" },
    { value: "1", label: "رشت" },
    { value: "2", label: "بندرانزلی" },
    { value: "3", label: "آستارا" },
    { value: "4", label: "لاهیجان" },
    { value: "5", label: "لوشان" },
    { value: "6", label: "هشت پر" },
    { value: "7", label: "بندر کیانشهر" },
    { value: "8", label: "کوچصفهان" },
    { value: "9", label: "کلاچای" },
    { value: "10", label: "آستانه اشرفيه" },
    { value: "11", label: "رضوان شهر" },
    { value: "12", label: "ماسال" },
    { value: "13", label: "طوالش" },
    { value: "14", label: "رستم آباد" },
    { value: "15", label: "رودبار" },
    { value: "16", label: "املش" },
    { value: "17", label: "رودسر" },
    { value: "18", label: "صومعه سرا" },
    { value: "19", label: "شفت" },
    { value: "20", label: "فومن" },
    { value: "21", label: "سیاهکل" },
    { value: "22", label: "لنگرود" },
    { value: "23", label: "اسالم" },
    { value: "24", label: "چابکسر" },
    { value: "25", label: "تالش" },
    { value: "26", label: "خشکبیجار" },
    { value: "27", label: "منجیل" },
    { value: "28", label: "سنگسر" },
  ],
  3: [
    { label: "تبریز", value: "1" },
    { label: "ممقان", value: "2" },
    { label: "خسرو شهر", value: "3" },
    { label: "خراجو", value: "4" },
    { label: "اهر", value: "5" },
    { label: "ورزقان", value: "6" },
    { label: "آذرشهر", value: "7" },
    { label: "اسکو", value: "8" },
    { label: "بستان آباد", value: "9" },
    { label: "شبستر", value: "10" },
    { label: "خاروانا", value: "11" },
    { label: "سراب", value: "12" },
    { label: "هادی شهر", value: "13" },
    { label: "کلیبر", value: "14" },
    { label: "بناب", value: "15" },
    { label: "عجب شیر", value: "16" },
    { label: "مراغه", value: "17" },
    { label: "ملکان", value: "18" },
    { label: "جلفا", value: "19" },
    { label: "مرند", value: "20" },
    { label: "ترکمنچای", value: "21" },
    { label: "میانه", value: "22" },
    { label: "هریس", value: "23" },
    { label: "چاراویماق", value: "24" },
    { label: "هشترود", value: "25" },
    { label: "قره اغاج", value: "26" },
    { label: "خدا آفرین", value: "27" },
    { label: "مهربان", value: "28" },
  ],
  4: [
    { label: "اهواز", value: "1" },
    { label: "بندرماهشهر", value: "2" },
    { label: "بندر امام خمینی", value: "3" },
    { label: "امیدیه", value: "4" },
    { label: "آبادان", value: "5" },
    { label: "صیدون", value: "6" },
    { label: "سردشت دزفول", value: "7" },
    { label: "اروند کنار", value: "8" },
    { label: "گتوند", value: "9" },
    { label: "شوشتر", value: "10" },
    { label: "لالی", value: "11" },
    { label: "مسجد سلیمان", value: "12" },
    { label: "شوش", value: "13" },
    { label: "لالی", value: "14" },
    { label: "مسجد سلیمان", value: "15" },
    { label: "شوش", value: "16" },
    { label: "حمیدیه", value: "17" },
    { label: "ایذه", value: "18" },
    { label: "اندیمشک", value: "19" },
    { label: "دهدز", value: "20" },
    { label: "باغملک", value: "21" },
    { label: "هویزه", value: "22" },
    { label: "هندیجان", value: "23" },
    { label: "بهبهان", value: "24" },
    { label: "خرمشهر", value: "25" },
    { label: "دزفول", value: "26" },
    { label: "دشت آزادگان", value: "27" },
    { label: "رامشیر", value: "28" },
    { label: "رامهرمز", value: "29" },
    { label: "شادگان", value: "31" },
    { label: "اغاجاری", value: "32" },
    { label: "بستان", value: "33" },
    { label: "سوسنگرد", value: "34" },
    { label: "الوان", value: "35" },
    { label: "شاوور", value: "36" },
    { label: "اندیکا(قلعه خواجو)", value: "37" },
    { label: "باوی", value: "38" },
  ],
  5: [
    { label: "شیراز", value: "1" },
    { label: "مرودشت", value: "2" },
    { label: "دشمن زیاری", value: "3" },
    { label: "فراشبند", value: "4" },
    { label: "قیروکارزین", value: "5" },
    { label: "فیروزآباد", value: "6" },
    { label: "بالاده", value: "7" },
    { label: "درودزن", value: "8" },
    { label: "شیب کوه", value: "9" },
    { label: "کازرون", value: "10" },
    { label: "فسا", value: "11" },
    { label: "سپیدان", value: "12" },
    { label: "زرقان", value: "13" },
    { label: "آباده طشک", value: "14" },
    { label: "لامرد", value: "15" },
    { label: "لارستان", value: "16" },
    { label: "مهر", value: "17" },
    { label: "داراب", value: "18" },
    { label: "زرین دشت", value: "19" },
    { label: "قائمیه", value: "20" },
    { label: "جهرم", value: "21" },
    { label: "اقلید", value: "22" },
    { label: "استهبان", value: "23" },
    { label: "ارسنجان", value: "24" },
    { label: "ممسنی (نورآباد)", value: "25" },
    { label: "نی ریز", value: "26" },
    { label: "سرچهان", value: "27" },
    { label: "پاسارگاد", value: "28" },
    { label: "قادرآباد", value: "29" },
    { label: "سمیکان", value: "30" },
    { label: "ایزدخواست", value: "31" },
    { label: "قطب آباد", value: "32" },
    { label: "خرم بید", value: "33" },
    { label: "آباده", value: "34" },
    { label: "کامفیروز", value: "35" },
    { label: "بیضا", value: "36" },
    { label: "اشکنان", value: "37" },
    { label: "مهر فارس", value: "38" },
    { label: "سعادت شهر", value: "39" },
    { label: "خاوران", value: "40" },
    { label: "صفا شهر", value: "41" },
    { label: "خنج", value: "42" },
    { label: "رستم", value: "42" },
    { label: "زاهد شهر", value: "44" },
    { label: "نودان", value: "45" },
    { label: "سروستان", value: "46" },
    { label: "خرامه", value: "47" },
    { label: "کوار", value: "48" },
    { label: "لار", value: "49" },
    { label: "بناب جدید", value: "50" },
    { label: "گراش", value: "51" },
  ],
  6: [
    { label: "اصفهان", value: "1" },
    { label: "کاشان", value: "2" },
    { label: "شاهین شهر (میمه)", value: "3" },
    { label: "شهررضا", value: "4" },
    { label: "گلپایگان", value: "5" },
    { label: "مبارکه", value: "6" },
    { label: "نایین", value: "7" },
    { label: "نجف آباد", value: "8" },
    { label: "نطنز", value: "9" },
    { label: "بهارستان", value: "10" },
    { label: "بن رود", value: "11" },
    { label: "نوش اباد", value: "12" },
    { label: "باغ شاد", value: "13" },
    { label: "زواره", value: "14" },
    { label: "ورزنه", value: "15" },
    { label: "حسن آباد جرقویه", value: "16" },
    { label: "کوهپایه", value: "17" },
    { label: "هرند", value: "18" },
    { label: "دولت آباد", value: "19" },
    { label: "خوراسگان", value: "20" },
    { label: "زاینده رود", value: "21" },
    { label: "دهاقان", value: "22" },
    { label: "گز", value: "23" },
    { label: "برزک", value: "24" },
    { label: "فولاد شهر", value: "25" },
    { label: "پیربکران", value: "26" },
    { label: "وزوان", value: "27" },
    { label: "بوئین و میاندشت", value: "28" },
    { label: "زرین شهر", value: "29" },
    { label: "میمه", value: "30" },
    { label: "باغ بهادران", value: "31" },
    { label: "خمینی شهر", value: "32" },
    { label: "اردستان", value: "33" },
    { label: "خوانسار", value: "34" },
    { label: "سمیرم", value: "35" },
    { label: "چادگان", value: "36" },
    { label: "فریدن", value: "37" },
    { label: "فریدون شهر", value: "38" },
    { label: "داران", value: "39" },
    { label: "فلاورجان", value: "40" },
    { label: "اران و بیدگل", value: "41" },
    { label: "لنجان", value: "42" },
    { label: "خور و بیابانک", value: "43" },
    { label: "تیران و کرون", value: "44" },
    { label: "مهردشت (علویجه)", value: "45" },
    { label: "قمصر", value: "46" },
  ],
  7: [
    { label: "مشهد", value: "1" },
    { label: "سبزوار", value: "2" },
    { label: "نیشابور", value: "3" },
    { label: "زبرخان بقدمگاه", value: "4" },
    { label: "عشق آباد", value: "5" },
    { label: "فیروزه", value: "6" },
    { label: " جوین - نقاب", value: "7" },
    { label: " کاخک", value: "8" },
    { label: " تخت جلگه", value: "9" },
    { label: "خواف", value: "10" },
    { label: "جغتای", value: "11" },
    { label: "تایباد", value: "12" },
    { label: " تربت جام", value: "13" },
    { label: "مه ولات - فیض آباد", value: "14" },
    { label: "تربت حدریه", value: "15" },
    { label: "بینالود", value: "16" },
    { label: "چناران", value: "17" },
    { label: "فریمان", value: "18" },
    { label: "کلات", value: "19" },
    { label: "بردسکن", value: "20" },
    { label: "خلیل آباد", value: "21" },
    { label: "کاشمر", value: "22" },
    { label: "قوچان", value: "23" },
    { label: "بجستان", value: "24" },
    { label: "گناباد", value: "25" },
    { label: "سرخس", value: "26" },
    { label: "درگز", value: "27" },
    { label: "درود", value: "28" },
    { label: "سرولایت", value: "29" },
    { label: "دوغارون", value: "30" },
    { label: "داورزن", value: "31" },
    { label: "گلبهار", value: "32" },
    { label: "دولت آباد زاوه", value: "33" },
    { label: "طرقبه", value: "34" },
    { label: "میان جلگه", value: "35" },
    { label: "رشتخوار", value: "36" },
  ],
  8: [
    { label: "قزوین", value: "1" },
    { label: "اوج", value: "2" },
    { label: "الوند", value: "3" },
    { label: "دانسفهان", value: "4" },
    { label: "شال", value: "5" },
    { label: "تاکستان", value: "6" },
    { label: "ابیک", value: "7" },
    { label: "ضیا آباد", value: "8" },
    { label: "بوئین زهرا", value: "9" },
    { label: "طارم سلفی", value: "10" },
    { label: "شهر صنعتی البرز", value: "11" },
  ],
  9: [
    { label: "سمنان", value: "1" },
    { label: "شاهرود", value: "2" },
    { label: "دامغان", value: "3" },
    { label: "بسطام", value: "4" },
    { label: "شهمیرزاد", value: "5" },
    { label: "گرمسار", value: "6" },
    { label: "سرخه", value: "7" },
    { label: "ارادان", value: "8" },
    { label: "میامی", value: "9" },
    { label: "مهدی شهر", value: "10" },
    { label: "ایوانکی", value: "11" },
    { label: "مجن", value: "12" },
  ],
  10: [
    { label: "قم", value: "1" },
    { label: "سلفچگان", value: "2" },
    { label: "جعفریه", value: "3" },
    { label: "دستجرد خلجستان", value: "4" },
    { label: "کهک", value: "5" },
  ],
  11: [
    { label: "اراک", value: "1" },
    { label: "سربند", value: "2" },
    { label: "شهرک صنعتی نوبران", value: "3" },
    { label: "خنداب", value: "4" },
    { label: "(چهار چشمه) قورچی باشی", value: "5" },
    { label: "غرق آباد", value: "6" },
    { label: "کمیجان", value: "7" },
    { label: "اشتیان", value: "8" },
    { label: "تفرش", value: "9" },
    { label: "خمین", value: "10" },
    { label: "دلیجان", value: "11" },
    { label: "زرندیه", value: "12" },
    { label: "ساوه", value: "13" },
    { label: "شازند", value: "14" },
    { label: "مهاجران", value: "15" },
    { label: "محلات", value: "16" },
  ],
  12: [
    { label: "زنجان", value: "1" },
    { label: "ابهر", value: "2" },
    { label: "صائین قلعه", value: "3" },
    { label: "قیدار", value: "4" },
    { label: "طارم", value: "5" },
    { label: "سلطانیه", value: "6" },
    { label: "ماه نشان", value: "7" },
    { label: "ایجرود (زرین آباد)", value: "8" },
    { label: "خدابنده", value: "9" },
    { label: "خرمدره", value: "10" },
    { label: "بزینه رود", value: "11" },
  ],
  13: [
    { label: "ساری", value: "1" },
    { label: "آمل", value: "2" },
    { label: "بابل", value: "3" },
    { label: "بابلسر", value: "4" },
    { label: "رامسر", value: "5" },
    { label: "چالوس", value: "6" },
    { label: "نوضهر", value: "7" },
    { label: "قائم شهر", value: "8" },
    { label: "محمو آباد", value: "9" },
    { label: "بندپی شرقی", value: "10" },
    { label: "کلاردشت", value: "11" },
    { label: "هراز", value: "12" },
    { label: "بهشهر", value: "13" },
    { label: "نکا", value: "14" },
    { label: "تنکابن", value: "15" },
    { label: "گلوگاه", value: "16" },
    { label: "سوادکوه", value: "17" },
    { label: "نور", value: "18" },
    { label: "بهنمیر", value: "19" },
    { label: "رینه", value: "20" },
    { label: "بندپی غربی", value: "21" },
    { label: "عباس آباد", value: "22" },
    { label: "فریدون کنار", value: "23" },
    { label: "کله بست", value: "24" },
    { label: "پل سفید", value: "25" },
    { label: "زیراب", value: "26" },
    { label: "چمستان", value: "27" },
    { label: "امیرکلا", value: "28" },
    { label: "میاندورود", value: "29" },
    { label: "جویبار", value: "30" },
  ],
  14: [
    { label: "گرگان", value: "1" },
    { label: "بندر ترکمن", value: "2" },
    { label: "گنبد کاووس", value: "3" },
    { label: "گمیشان", value: "4" },
    { label: "مراوه تپه", value: "5" },
    { label: "بندرگز", value: "6" },
    { label: "کردکوی", value: "7" },
    { label: "اق قلا", value: "8" },
    { label: "گالیکش", value: "9" },
    { label: "آزادشهر", value: "10" },
    { label: "رامیاران", value: "11" },
    { label: "مینودشت", value: "12" },
    { label: "علی آباد کتول", value: "13" },
    { label: "کلاله", value: "14" },
  ],
  15: [
    { label: "اردبیل", value: "1" },
    { label: "سرعین", value: "2" },
    { label: "مشکین شهر", value: "3" },
    { label: "بیله سوار", value: "4" },
    { label: "پارس آباد", value: "5" },
    { label: "گرمی", value: "6" },
    { label: " تازه انگوت", value: "7" },
    { label: " ارشق (رضی)", value: "8" },
    { label: " کوثر", value: "9" },
    { label: "هیر", value: "10" },
    { label: "خلخال", value: "11" },
    { label: "نمین", value: "12" },
    { label: "مغان", value: "13" },
    { label: "اصلاندوز", value: "14" },
  ],
  16: [
    { label: "ارومیه", value: "1" },
    { label: "سیلوانا", value: "2" },
    { label: " صومای برادوست", value: "3" },
    { label: "نازلو", value: "4" },
    { label: "گوگ تپه", value: "5" },
    { label: "ابواوغلی", value: "6" },
    { label: "چهاربرج", value: "7" },
    { label: "سیه چشمه", value: "8" },
    { label: "تازه شهر", value: "9" },
    { label: "شوط", value: "10" },
    { label: "چایپاره", value: "11" },
    { label: "پیرانشهر", value: "12" },
    { label: " سلماس", value: "13" },
    { label: "پلدشت", value: "14" },
    { label: "چالدران", value: "15" },
    { label: "ماکو", value: "16" },
    { label: "قره ضیاء الدین", value: "17" },
    { label: "بوکان", value: "18" },
    { label: "خوی", value: "19" },
    { label: "سردشت", value: "20" },
    { label: "مهاباد", value: "21" },
    { label: "تکاب", value: "22" },
    { label: "شاهین دژ", value: "23" },
    { label: "میاندوآب", value: "24" },
    { label: "اشنویه", value: "25" },
    { label: "نقده", value: "26" },
  ],
  17: [
    { label: "همدان", value: "1" },
    { label: "قروه ", value: "2" },
    { label: "سامن", value: "3" },
    { label: "لالیجن", value: "4" },
    { label: "صالح آباد", value: "5" },
    { label: "تویسرکان", value: "6" },
    { label: "کبودرآهنگ", value: "7" },
    { label: "ملایر", value: "8" },
    { label: " نهاوند", value: "9" },
    { label: "اسد آباد", value: "10" },
    { label: "رزن", value: "11" },
    { label: "بهار", value: "12" },
  ],
  18: [
    { label: "سنندج", value: "1" },
    { label: "سقز", value: "2" },
    { label: "دیواندره", value: "3" },
    { label: "کامیاران", value: "4" },
    { label: "قروه", value: "5" },
    { label: "دهگلان", value: "6" },
    { label: "سروآباد", value: "7" },
    { label: "مریوان", value: "8" },
    { label: "بانه", value: "9" },
    { label: "بیجار", value: "10" },
  ],
  19: [
    { label: "کرمانشاه", value: "1" },
    { label: "تازه آباد", value: "2" },
    { label: "گلانغرب", value: "3" },
    { label: "کنگاور", value: "4" },
    { label: "قصر شیرین", value: "5" },
    { label: "سنقر", value: "6" },
    { label: "پاوه ", value: "7" },
    { label: "جوانرود ", value: "8" },
    { label: "روانسر ", value: "9" },
    { label: "سرپل ذهاب", value: "10" },
    { label: "صحنه", value: "11" },
    { label: "اسلام آباد غرب", value: "12" },
    { label: " هرسین", value: "13" },
    { label: "ثلاث باباجانی", value: "14" },
    { label: "دالاهو", value: "15" },
  ],
  20: [
    { label: "خرم آباد", value: "1" },
    { label: "بروجرد", value: "2" },
    { label: "الشتر", value: "3" },
    { label: "دروه", value: "4" },
    { label: "ازنا", value: "5" },
    { label: "الیگودرز", value: "6" },
    { label: "سلسله ", value: "7" },
    { label: "پلدختر", value: "8" },
    { label: "دورود", value: "9" },
    { label: "دلفان (نورآباد)", value: "10" },
    { label: "رومشکان", value: "11" },
    { label: "کوهدشت", value: "12" },
  ],
  21: [
    { label: "بوشهر", value: "1" },
    { label: "جم", value: "2" },
    { label: "سعدآباد", value: "3" },
    { label: "دلوار", value: "4" },
    { label: "بندر دیر", value: "5" },
    { label: "اهرم(تنگستان)", value: "6" },
    { label: "عسلویه", value: "7" },
    { label: "دشتی خورموج", value: "8" },
    { label: "دیر(بردخون)", value: "9" },
    { label: "دیلم", value: "10" },
    { label: "بندر گناوه", value: "11" },
    { label: "شبانکاره", value: "12" },
    { label: "دشتستان (برازجان)", value: "13" },
    { label: "کنگان", value: "14" },
  ],
  22: [
    { label: "کرمان", value: "1" },
    { label: "رودبار جنوب", value: "2" },
    { label: "بافت", value: "3" },
    { label: "بردسیر", value: "4" },
    { label: "بم", value: "5" },
    { label: "عنبرآباد", value: "6" },
    { label: "جیرفت", value: "7" },
    { label: "رفسنجان", value: "8" },
    { label: "کوهبنان", value: "9" },
    { label: "زرند", value: "10" },
    { label: "سیرجان", value: "11" },
    { label: "شهربابک", value: "12" },
    { label: "قلعه گنج", value: "13" },
    { label: "راور", value: "14" },
    { label: "کهنوج", value: "15" },
    { label: "منوجان", value: "16" },
    { label: "ماهان", value: "17" },
    { label: "فاریاب", value: "18" },
    { label: "پاریز", value: "19" },
    { label: "نگار", value: "20" },
    { label: "رابر", value: "21" },
    { label: "نرماشیر", value: "22" },
    { label: "فهرج", value: "23" },
    { label: "راین", value: "24" },
    { label: "شهداد", value: "25" },
    { label: "انار", value: "26" },
    { label: "کشکوییه", value: "27" },
    { label: "ریگان", value: "28" },
    { label: "زنگی آباد", value: "29" },
    { label: "گلباف", value: "30" },
  ],
  23: [
    { label: "بندرعباس", value: "1" },
    { label: "کیش", value: "2" },
    { label: "ابوموسی", value: "3" },
    { label: "قشم", value: "4" },
    { label: "حاجی آباد", value: "5" },
    { label: "بستک", value: "6" },
    { label: "بندر لنگه", value: "7" },
    { label: "جاسک", value: "8" },
    { label: "میناب", value: "9" },
    { label: "جناح", value: "10" },
    { label: "شهاب", value: "11" },
    { label: "پارسیان", value: "12" },
    { label: "بیابان سیریک", value: "13" },
    { label: "بندر خمیر", value: "14" },
    { label: "دهبارز (رودان)", value: "15" },
    { label: "فین", value: "16" },
    { label: "بشاگرد", value: "17" },
    { label: "سعادت آباد", value: "18" },
  ],
  24: [
    { label: "شهرکرد", value: "1" },
    { label: "خانمیرزا", value: "2" },
    { label: "فلارد", value: "3" },
    { label: "کوهرنگ", value: "4" },
    { label: "فارسان", value: "5" },
    { label: "لردگان", value: "6" },
    { label: "اردل", value: "7" },
    { label: "بروجن", value: "8" },
    { label: "کیار", value: "9" },
    { label: "شلمزار", value: "10" },
    { label: "سامان", value: "11" },
    { label: "فرخ بخش", value: "12" },
    { label: "بلداجی", value: "13" },
    { label: "گندمان", value: "14" },
  ],
  25: [
    { label: "یزد", value: "1" },
    { label: "اردکان", value: "2" },
    { label: "میبد", value: "3" },
    { label: "بافق", value: "4" },
    { label: "لبرکوه", value: "5" },
    { label: "تفت", value: "6" },
    { label: "مهرریز", value: "7" },
    { label: "خاتم", value: "8" },
    { label: "اشکذر", value: "9" },
    { label: "مروست", value: "10" },
    { label: "بهاباد", value: "11" },
    { label: "هرات", value: "12" },
  ],
  26: [
    { label: "زاهدان", value: "1" },
    { label: "زابل", value: "2" },
    { label: "هیرمند", value: "3" },
    { label: "راسک", value: "4" },
    { label: "سیب وسوران", value: "5" },
    { label: "زهک", value: "6" },
    { label: "سرباز", value: "7" },
    { label: "ایرانشهر", value: "8" },
    { label: "چابهار", value: "9" },
    { label: "نیک شهر", value: "10" },
    { label: "خاش", value: "11" },
    { label: "شهرکی و نارویی", value: "12" },
    { label: "سراوان", value: "13" },
    { label: "دشتیاری", value: "14" },
    { label: "بمپور", value: "15" },
    { label: "دلگان", value: "16" },
    { label: "زابلی", value: "17" },
    { label: "پشت آب", value: "18" },
    { label: "شیب آب", value: "19" },
    { label: "قصرقند", value: "20" },
    { label: "لاشار", value: "21" },
    { label: "کنارک", value: "22" },
  ],
  27: [
    { label: "ایلام", value: "1" },
    { label: "ایوان", value: "2" },
    { label: "آبدانان  ", value: "3" },
    { label: "دره شهر", value: "4" },
    { label: "شیروان و چرداول", value: "5" },
    { label: "دهلران", value: "6" },
    { label: "مهران", value: "7" },
    { label: "بدره", value: "8" },
    { label: "سیروان", value: "9" },
    { label: "موسیان", value: "10" },
    { label: "سرآبله", value: "11" },
    { label: "زرین آباد", value: "12" },
    { label: "هلیلان", value: "13" },
    { label: "ملکشاهی", value: "14" },
  ],
  28: [
    { label: "بویراحمد (یاسوج)", value: "1" },
    { label: "گچساران", value: "2" },
    { label: "دنا", value: "3" },
    { label: "بهمئی", value: "4" },
    { label: "دهدشت (کهگیلویه)", value: "5" },
    { label: "سی سخت", value: "6" },
    { label: "دو گنبدان", value: "7" },
    { label: "چرام", value: "8" },
    { label: "لیکک", value: "9" },
    { label: "باشت", value: "10" },
    { label: "مارگون", value: "11" },
  ],
  29: [
    { label: "بجنورد", value: "1" },
    { label: "اشخانه", value: "2" },
    { label: "رازوجرگلان", value: "3" },
    { label: "گرمه", value: "4" },
    { label: "اسفراین", value: "5" },
    { label: "جاجرم", value: "6" },
    { label: "مانه و سملقان", value: "7" },
    { label: "شیروان", value: "8" },
    { label: "فاروج ", value: "9" },
    { label: "غلامان", value: "10" },
  ],
  30: [
    { label: "بیرجند", value: "1" },
    { label: "طبس", value: "2" },
    { label: "فردوس", value: "3" },
    { label: "حاجی آباد", value: "4" },
    { label: "قائنات", value: "5" },
    { label: "بشرویه", value: "6" },
    { label: " نهبندان", value: "7" },
    { label: "سربیشه", value: "8" },
    { label: "زیرکوه", value: "9" },
    { label: "قائن", value: "10" },
    { label: "اسدیه", value: "11" },
    { label: "درمیان", value: "12" },
  ],
  31: [
    { label: "کرج", value: "1" },
    { label: "فردیس کرج", value: "2" },
    { label: "طالقان", value: "3" },
    { label: "هشتگرد", value: "4" },
    { label: "اشتهارد", value: "5" },
    { label: "گرمدره", value: "6" },
    { label: "ماهدشت", value: "7" },
    { label: "ساوجبلاغ", value: "8" },
    { label: "نظرآباد", value: "9" },
  ],
  32: [
    { label: "خاورمیانه", value: "1" },
    { label: "اروپا", value: "2" },
    { label: "اسیای شرقی", value: "3" },
    { label: "امریکای شمالی", value: "4" },
    { label: "امریکای جنوبی", value: "5" },
    { label: "استرالیا", value: "6" },
  ],
};

export const CityOptions = [
  { value: "1", label: "تهران" }, //1
  { value: "2", label: "گیلان" }, //11
  { value: "3", label: "آذربایجان شرقی" }, //10
  { value: "4", label: "خوزستان" }, //13
  { value: "5", label: "فارس" }, //5
  { value: "6", label: "اصفهان" }, //2
  { value: "7", label: "خراسان رضوی" }, //4
  // { value: "8", label: "اصفهان" },
  { value: "8", label: "قزوین" }, //7
  { value: "9", label: "سمنان" }, //18
  { value: "10", label: "قم" }, //6
  { value: "11", label: "مرکزی" }, //14
  { value: "12", label: "زنجان" }, //17
  { value: "13", label: "مازندران" }, //8
  { value: "14", label: "گلستان" }, //28
  { value: "15", label: "اردبیل" }, //16
  { value: "16", label: "آذربایجان غربی" }, //15
  { value: "17", label: "همدان" }, //31
  { value: "18", label: "کردستان" }, //25
  { value: "19", label: "کرمانشاه" }, //26
  { value: "20", label: "لرستان" }, //29
  { value: "21", label: "بوشهر" }, //20
  { value: "22", label: "کرمان" }, //9
  { value: "23", label: "هرمزگان" }, //30
  { value: "24", label: "چهارمحال و بختیاری" }, //21
  { value: "25", label: "یزد" }, //12
  { value: "26", label: "سیستان و بلوچستان" }, //24
  { value: "27", label: "ایلام" }, //19
  { value: "28", label: "کهگلویه و بویراحمد" }, //27
  { value: "29", label: "خراسان شمالی" }, //22
  { value: "30", label: "خراسان جنوبی" }, //23
  { value: "31", label: "البرز" }, //3
  { value: "32", label: "خارج کشور" }, //3
];
